apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: efe32ry1m-python
  janus-idp.io/tekton: efe32ry1m-python
  backstage.io/kubernetes-id: efe32ry1m-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: efe32ry1m-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
